import type { ReactNode } from 'react';
import Link from 'next/link';

export const metadata = {
  title: 'User Terms & Conditions — Quizzaroo',
  description: 'Terms that govern how to use the Quizzaroo learning experience.',
};

const updatedOn = 'October 19, 2025';

interface Section {
  heading: string;
  body: ReactNode[];
}

const sections: Section[] = [
  {
    heading: '1. Acceptance of Terms',
    body: [
      'Quizzaroo is an experimental learning assistant that generates multiple-choice practice powered by large language models (LLMs). By accessing or using the site you agree to these Terms & Conditions and any policies referenced here. If you do not agree, you must stop using the product immediately.',
    ],
  },
  {
    heading: '2. Who May Use Quizzaroo',
    body: [
      'The app is intended for learners 13+ who can safely handle AI-generated study material. Educators or coaches may use Quizzaroo to support learners, provided they share these terms with their participants and supervise minors as required by local law.',
    ],
  },
  {
    heading: '3. Account-Free Experience',
    body: [
      'Quizzaroo does not require a login and does not persist quizzes on our servers. Session data (selected settings, cached API keys, quiz state) stays in the current browser tab. If you reload, close the tab, or clear storage, your progress disappears.',
    ],
  },
  {
    heading: '4. AI-Generated Content',
    body: [
      'Quiz questions, answers, explanations, and study plans are generated by third-party LLM APIs such as Azure OpenAI or Perplexity. While we apply guardrails and validation checks, model outputs may still contain mistakes, outdated information, or sensitive subject matter. Use your judgment, especially in professional or high-stakes settings.',
      'You are responsible for reviewing questions before sharing them with learners and for verifying any factual claims that matter to you.',
    ],
  },
  {
    heading: '5. Your Responsibilities',
    body: [
      'Use Quizzaroo only for lawful study and coaching scenarios.',
      'Do not attempt to reverse engineer, overload, or disrupt the service or underlying APIs.',
      'Do not input personal data that you do not have permission to share (for example, student records, protected health information, or confidential business data).',
    ],
  },
  {
    heading: '6. Availability & Changes',
    body: [
      'We may update the UI, prompts, or API providers without notice. Planned outages or major changes will be announced in the project README when possible.',
      'We may suspend or terminate access if we detect abuse, security risk, or violation of these terms.',
    ],
  },
  {
    heading: '7. Disclaimers & Limitation of Liability',
    body: [
      'Quizzaroo is provided “as is” without warranties of any kind. We expressly disclaim all implied warranties, including fitness for a particular purpose, accuracy, or reliability of results.',
      'To the maximum extent permitted by law, Quizzaroo and its maintainers are not liable for any indirect, consequential, incidental, special, or punitive damages, nor for lost profits or data arising from your use of the app.',
    ],
  },
  {
    heading: '8. Third-Party Services',
    body: [
      'When you supply an Azure or Perplexity API key, requests are sent directly to those providers. Their terms of service and privacy policies govern that usage. Ensure your key usage complies with your agreements with Microsoft, OpenAI, or Perplexity.',
    ],
  },
  {
    heading: '9. Updates to These Terms',
    body: [
      'We may revise these terms to reflect new features or legal requirements. Material changes will be noted with a new “Last updated” date. Continued use after changes become effective constitutes acceptance of the revised terms.',
    ],
  },
  {
    heading: '10. Contact',
    body: [
      <>
        For questions about these terms, reach out via email at{' '}
        <Link href="mailto:architmishrapro@gmail.com">architmishrapro@gmail.com</Link>.
      </>,
    ],
  },
];

export default function TermsPage() {
  return (
    <div className="card">
      <h2>Quizzaroo User Terms &amp; Conditions</h2>
      <p className="muted">Last updated {updatedOn}</p>
      <div className="mt-3 row" style={{ gap: 20 }}>
        {sections.map((section) => (
          <section key={section.heading}>
            <h3>{section.heading}</h3>
            {section.body.map((entry, idx) => (
              <p key={idx}>{entry}</p>
            ))}
          </section>
        ))}
      </div>
    </div>
  );
}
